namespace PoundPupLegacy.CreateModel;

public sealed record NewCountryAndFirstAndBottomLevelSubdivision : NewCountryAndSubdivisionBase, EventuallyIdentifiableCountryAndFirstAndBottomLevelSubdivision
{
}
public sealed record ExistingCountryAndFirstAndBottomLevelSubdivision : ExistingCountryAndSubdivisionBase, ImmediatelyIdentifiableCountryAndFirstAndBottomLevelSubdivision
{
}
public interface EventuallyIdentifiableCountryAndFirstAndBottomLevelSubdivision : EventuallyIdentifiableCountryAndFirstLevelSubdivision, EventuallyIdentifiableBottomLevelSubdivision
{
}
public interface ImmediatelyIdentifiableCountryAndFirstAndBottomLevelSubdivision : ImmediatelyIdentifiableCountryAndFirstLevelSubdivision, ImmediatelyIdentifiableBottomLevelSubdivision
{
}
public interface CountryAndFirstAndBottomLevelSubdivision: CountryAndFirstLevelSubdivision, BottomLevelSubdivision
{
}
