namespace PoundPupLegacy.CreateModel;

public sealed record NewCountryAndIntermediateLevelSubdivision : NewCountryAndSubdivisionBase, EventuallyIdentifiableCountryAndIntermediateLevelSubdivision
{
}
public sealed record ExistingCountryAndIntermediateLevelSubdivision : ExistingCountryAndSubdivisionBase, ImmediatelyIdentifiableCountryAndIntermediateLevelSubdivision
{
}

public interface ImmediatelyIdentifiableCountryAndIntermediateLevelSubdivision : CountryAndIntermediateLevelSubdivision, ImmediatelyIdentifiableCountryAndSubdivision, ImmediatelyIdentifiableISOCodedFirstLevelSubdivision, ImmediatelyIdentifiableIntermediateLevelSubdivision, ImmediatelyIdentifiableCountryAndFirstLevelSubdivision
{

}
public interface EventuallyIdentifiableCountryAndIntermediateLevelSubdivision : CountryAndIntermediateLevelSubdivision, EventuallyIdentifiableCountryAndSubdivision, EventuallyIdentifiableISOCodedFirstLevelSubdivision, EventuallyIdentifiableIntermediateLevelSubdivision, EventuallyIdentifiableCountryAndFirstLevelSubdivision
{

}
public interface CountryAndIntermediateLevelSubdivision: CountryAndSubdivision, ISOCodedFirstLevelSubdivision, IntermediateLevelSubdivision, CountryAndFirstLevelSubdivision
{

}
