namespace PoundPupLegacy.CreateModel;

public sealed record NewCountryAndFirstAndSecondLevelSubdivision : NewCountryAndSubdivisionBase, EventuallyIdentifiableCountryAndFirstAndSecondLevelSubdivision
{
}
public sealed record ExistingCountryAndFirstAndSecondLevelSubdivision : ExistingCountryAndSubdivisionBase, ImmediatelyIdentifiableCountryAndFirstAndSecondLevelSubdivision
{
}

public interface ImmediatelyIdentifiableCountryAndFirstAndSecondLevelSubdivision : CountryAndFirstAndSecondLevelSubdivision, ImmediatelyIdentifiableCountryAndFirstLevelSubdivision, ImmediatelyIdentifiableFirstAndSecondLevelSubdivision
{
}

public interface EventuallyIdentifiableCountryAndFirstAndSecondLevelSubdivision : CountryAndFirstAndSecondLevelSubdivision, EventuallyIdentifiableCountryAndFirstLevelSubdivision, EventuallyIdentifiableFirstAndSecondLevelSubdivision
{
}

public interface CountryAndFirstAndSecondLevelSubdivision: CountryAndFirstLevelSubdivision, FirstAndSecondLevelSubdivision
{
}
