namespace PoundPupLegacy.CreateModel;

public sealed record NewFirstAndBottomLevelSubdivision : NewISOCodedSubdivisionBase, EventuallyIdentifiableFirstAndBottomLevelSubdivision
{

}
public sealed record ExistingFirstAndBottomLevelSubdivision : ExistingISOCodedSubdivisionBase, ImmediatelyIdentifiableFirstAndBottomLevelSubdivision
{

}
public interface ImmediatelyIdentifiableFirstAndBottomLevelSubdivision : FirstAndBottomLevelSubdivision, ImmediatelyIdentifiableISOCodedFirstLevelSubdivision, ImmediatelyIdentifiableBottomLevelSubdivision
{
}

public interface EventuallyIdentifiableFirstAndBottomLevelSubdivision : FirstAndBottomLevelSubdivision,  EventuallyIdentifiableISOCodedFirstLevelSubdivision, EventuallyIdentifiableBottomLevelSubdivision
{
}

public interface FirstAndBottomLevelSubdivision : ISOCodedFirstLevelSubdivision, BottomLevelSubdivision
{
}
