namespace PoundPupLegacy.CreateModel;
public interface ImmediatelyIdentifiableFirstAndSecondLevelSubdivision : FirstAndSecondLevelSubdivision, ImmediatelyIdentifiableISOCodedSubdivision, ImmediatelyIdentifiableSecondLevelSubdivision
{
}

public interface EventuallyIdentifiableFirstAndSecondLevelSubdivision : FirstAndSecondLevelSubdivision, EventuallyIdentifiableISOCodedSubdivision, EventuallyIdentifiableSecondLevelSubdivision 
{ 
}

public interface FirstAndSecondLevelSubdivision : ISOCodedFirstLevelSubdivision, SecondLevelSubdivision
{
}
