namespace PoundPupLegacy.CreateModel;

public sealed record NewFormalIntermediateLevelSubdivision : NewISOCodedSubdivisionBase, EventuallyIdentifiableFormalIntermediateLevelSubdivision
{
}
public sealed record ExistingormalIntermediateLevelSubdivision : ExistingISOCodedSubdivisionBase, ImmediatelyIdentifiableFormalIntermediateLevelSubdivision
{
}
public interface ImmediatelyIdentifiableFormalIntermediateLevelSubdivision : FormalIntermediateLevelSubdivision, ImmediatelyIdentifiableISOCodedFirstLevelSubdivision, ImmediatelyIdentifiableIntermediateLevelSubdivision
{
}
public interface EventuallyIdentifiableFormalIntermediateLevelSubdivision : FormalIntermediateLevelSubdivision , EventuallyIdentifiableISOCodedFirstLevelSubdivision, EventuallyIdentifiableIntermediateLevelSubdivision
{
}
public interface FormalIntermediateLevelSubdivision : ISOCodedFirstLevelSubdivision, IntermediateLevelSubdivision
{
}
