namespace PoundPupLegacy.CreateModel;

public sealed record NewInformalIntermediateLevelSubdivision : NewSubdivisionBase, EventuallyIdentifiableInformalIntermediateLevelSubdivision
{
}
public sealed record ExistingInformalIntermediateLevelSubdivision : ExistingSubdivisionBase, ImmediatelyIdentifiableInformalIntermediateLevelSubdivision
{
}
public interface ImmediatelyIdentifiableInformalIntermediateLevelSubdivision : InformalIntermediateLevelSubdivision, ImmediatelyIdentifiableIntermediateLevelSubdivision
{
}
public interface EventuallyIdentifiableInformalIntermediateLevelSubdivision : InformalIntermediateLevelSubdivision, EventuallyIdentifiableIntermediateLevelSubdivision
{
}
public interface InformalIntermediateLevelSubdivision: IntermediateLevelSubdivision
{
}
