namespace PoundPupLegacy.CreateModel;

public sealed record NewInterOrganizationalRelationType : NewEndoRelationTypeBase, EventuallyIdentifiableInterOrganizationalRelationType
{
}
public sealed record ExistingInterOrganizationalRelationType : ExistingEndoRelationTypeBase, ImmediatelyIdentifiableInterOrganizationalRelationType
{
}
public interface ImmediatelyIdentifiableInterOrganizationalRelationType : InterOrganizationalRelationType, ImmediatelyIdentifiableEndoRelationType
{
}
public interface EventuallyIdentifiableInterOrganizationalRelationType : InterOrganizationalRelationType, EventuallyIdentifiableEndoRelationType
{
}
public interface InterOrganizationalRelationType : EndoRelationType
{
}
