global using Npgsql;
global using PoundPupLegacy.CreateModel.Creators;
global using PoundPupLegacy.EditModel.Deleters;
global using PoundPupLegacy.EditModel.Inserters;
global using PoundPupLegacy.EditModel.Readers;
global using PoundPupLegacy.EditModel.Updaters;
global using System.Data;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.InterOrganizationalRelationFrom.CompletedInterOrganizationalRelationFrom.ResolvedInterOrganizationalRelationFrom;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.InterOrganizationalRelationFrom.CompletedInterOrganizationalRelationFrom;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.InterOrganizationalRelationTo.CompletedInterOrganizationalRelationTo.ResolvedInterOrganizationalRelationTo;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.InterOrganizationalRelationTo.CompletedInterOrganizationalRelationTo;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.InterPersonalRelationFrom.CompletedInterPersonalRelationFrom.ResolvedInterPersonalRelationFrom;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.InterPersonalRelationFrom.CompletedInterPersonalRelationFrom;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.InterPersonalRelationTo.CompletedInterPersonalRelationTo.ResolvedInterPersonalRelationTo;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.InterPersonalRelationTo.CompletedInterPersonalRelationTo;
global using static PoundPupLegacy.EditModel.OrganizationItem;
global using static PoundPupLegacy.EditModel.OrganizationPoliticalEntityRelation.CompletedOrganizationPoliticalEntityRelation.ResolvedOrganizationPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.PersonItem;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation.CompletedPersonPoliticalEntityRelation.ResolvedPersonPoliticalEntityRelation;


