global using Npgsql;
global using PoundPupLegacy.Common;
global using System.Text.Json.Serialization;

global using static PoundPupLegacy.EditModel.InterPersonalRelation;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.CompletedInterPersonalRelation;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.CompletedInterPersonalRelation.CompletedNewInterPersonalRelation;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.CompletedInterPersonalRelation.ResolvedInterPersonalRelation;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.IncompleteNewInterPersonalRelation.IncompleteNewInterPersonalFromRelation;

global using static PoundPupLegacy.EditModel.InterOrganizationalRelation;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.NewIncompleteInterOrganizationalRelationTo;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.NewIncompleteInterOrganizationalRelationFrom;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.CompletedInterOrganizationalRelation;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.CompletedInterOrganizationalRelation.ResolvedInterOrganizationalRelation;
global using static PoundPupLegacy.EditModel.InterOrganizationalRelation.CompletedInterOrganizationalRelation.CompletedNewInterOrganizationalRelation;

global using static PoundPupLegacy.EditModel.PersonItem;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForPerson;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForPerson.CompletedPersonOrganizationRelationForPerson;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForPerson.CompletedPersonOrganizationRelationForPerson.ResolvedPersonOrganizationRelationForPerson;

global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForOrganization;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForOrganization.CompletedPersonOrganizationRelationForOrganization;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForOrganization.CompletedPersonOrganizationRelationForOrganization.ResolvedPersonOrganizationRelationForOrganization;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.IncompleteNewInterPersonalRelation.IncompleteNewInterPersonalToRelation;
global using static PoundPupLegacy.EditModel.InterPersonalRelation.IncompleteNewInterPersonalRelation;


global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation.IncompletePersonPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation.CompletedPersonPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation.CompletedPersonPoliticalEntityRelation.ResolvedPersonPoliticalEntityRelation;

global using static PoundPupLegacy.EditModel.OrganizationItem;
global using static PoundPupLegacy.EditModel.OrganizationPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.OrganizationPoliticalEntityRelation.IncompleteOrganizationPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.OrganizationPoliticalEntityRelation.CompletedOrganizationPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.OrganizationPoliticalEntityRelation.CompletedOrganizationPoliticalEntityRelation.ResolvedOrganizationPoliticalEntityRelation;


