global using Npgsql;
global using PoundPupLegacy.Common;
global using System.Text.Json.Serialization;
global using static PoundPupLegacy.EditModel.Location;
global using static PoundPupLegacy.EditModel.OrganizationItem;
global using static PoundPupLegacy.EditModel.PersonItem;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForOrganization;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForOrganization.IncompletePersonOrganizationRelationForOrganization;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForOrganization.CompletedPersonOrganizationRelationForOrganization;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForOrganization.CompletedPersonOrganizationRelationForOrganization.ResolvedPersonOrganizationRelationForOrganization;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForPerson;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForPerson.IncompletePersonOrganizationRelationForPerson;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForPerson.CompletedPersonOrganizationRelationForPerson;
global using static PoundPupLegacy.EditModel.PersonOrganizationRelation.PersonOrganizationRelationForPerson.CompletedPersonOrganizationRelationForPerson.ResolvedPersonOrganizationRelationForPerson;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation.CompletedPersonPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation.CompletedPersonPoliticalEntityRelation.ResolvedPersonPoliticalEntityRelation;
global using static PoundPupLegacy.EditModel.PersonPoliticalEntityRelation.IncompletePersonPoliticalEntityRelation;


